#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  main:
    banner-mode: off

# 配置mybatis-plus
mybatis-plus:
  configuration:
    # 配置MyBatis自带日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mybatis-plus的全局配置
  global-config:
    banner: off

    db-config:
      #设置实体类对应的表的统一前缀(法2)
      table-prefix: t_
      #设置统一的主键生成策略
      id-type: auto
      #注意: mybatis-plus中字段映射是默认开启的(user_name=userName)
  # 配置类型别名所对应的包
  type-aliases-package: com.localhost.pojo
  # 已经不需要扫描枚举的包了, 会自动扫描
  # type-enums-package: com.localhost.enums