#打开浏览器属性
OpenURL:
  auto:
    #是否自动打开浏览器
    openurl: true
  web:
    #访问的网址
    loginUrl: http:/localhost:8080/books.html
    #浏览器的执行文件
    chromeExe: C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe